
// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.

// auto generated by generate.py
#include <cstdio>

#include <hip/hip_runtime.h>

#include "fmha_fwd.hpp"

namespace {
bool get_num_cus(unsigned& num_cus)
{
    int device;
    auto status = hipGetDevice(&device);
    if(status != hipSuccess)
    {
        fprintf(stderr, "failed to get device");
        return false;
    }

    hipDeviceProp_t props{};
    status = hipGetDeviceProperties(&props, device);
    if(status != hipSuccess)
    {
        fprintf(stderr, "failed to get device properties");
        return false;
    }

    num_cus = props.multiProcessorCount;
    return true;
}

unsigned get_num_thread_blocks(unsigned batch, unsigned nheads, unsigned max_seqlen_q, unsigned kM0)
{
    const unsigned num_m_blocks = (max_seqlen_q + kM0 - 1) / kM0;
    const unsigned num_n_blocks = 1; // we assume that num_n_blocks is always 1

    return batch * nheads * num_m_blocks * num_n_blocks;
}
} // namespace

namespace ck_tile {
float fmha_fwd_v3([[maybe_unused]] fmha_fwd_traits t,
                  [[maybe_unused]] fmha_fwd_args a,
                  [[maybe_unused]] const ck_tile::stream_config& s)
{
    float r = -1;

    [[maybe_unused]] const float min_cu_util_rate = 0.8; // minimum CU utilization rate

    unsigned num_cus;
    if(!get_num_cus(num_cus))
    {
        return r;
    }

    [[maybe_unused]] auto get_num_blocks = [&](unsigned kM0) {
        return get_num_thread_blocks(a.batch, a.nhead_q, a.max_seqlen_q, kM0);
    };

    [[maybe_unused]] const std::string device_name = ck_tile::get_device_name();

    if(device_name.compare(0, 6, "gfx950") == 0)
    {
        if(t.data_type.compare("fp16") == 0)
        {
            if(t.hdim_q <= 128 && t.hdim_v <= 128)
            {
                if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                   (t.has_logits_soft_cap == true) && (t.mask_type == mask_enum::no_mask) &&
                   (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                   (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                   (t.skip_min_seqlen_q == false) && (true) &&
                   (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                   (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == true) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true) &&
                        (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) && (t.mask_type == mask_enum::no_mask) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true) &&
                        (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true) &&
                        (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == true) && (t.mask_type == mask_enum::no_mask) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == true) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) && (t.mask_type == mask_enum::no_mask) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdFp16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
            }
        }
        else if(t.data_type.compare("bf16") == 0)
        {
            if(t.hdim_q <= 128 && t.hdim_v <= 128)
            {
                if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                   (t.has_logits_soft_cap == true) && (t.mask_type == mask_enum::no_mask) &&
                   (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                   (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                   (t.skip_min_seqlen_q == false) && (true) &&
                   (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                   (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == true) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true) &&
                        (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) && (t.mask_type == mask_enum::no_mask) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true) &&
                        (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == false) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true) &&
                        (true /*fall back to largest tile*/) && (true) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         false,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == true) && (t.mask_type == mask_enum::no_mask) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == true) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         true,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) && (t.mask_type == mask_enum::no_mask) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::NoMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
                else if((t.is_group_mode == true) && (t.is_v_rowmajor == true) &&
                        (t.has_logits_soft_cap == false) &&
                        (t.mask_type == mask_enum::mask_top_left ||
                         t.mask_type == mask_enum::mask_bottom_right) &&
                        (t.bias_type == bias_enum::no_bias) && (t.has_lse == false) &&
                        (t.has_dropout == false) && (t.qscale_type == quant_scale_enum::no_scale) &&
                        (t.skip_min_seqlen_q == false) && (true /*group mode spad always true*/) &&
                        (true /*fall back to largest tile*/) &&
                        (true /*group mode skpad always true*/) && (a.hdim_q % 128 == 0) &&
                        (a.hdim_v % 128 == 0) && ((true) && (true)))
                {
                    using trait_ =
                        fmha_fwd_traits_<128,
                                         FmhaFwdBf16,
                                         true,
                                         256,
                                         64,
                                         128,
                                         128,
                                         64,
                                         128,
                                         true,
                                         ck_tile::BlockFmhaPipelineEnum::QRKSVS_ASYNC_TRLOAD_V3,
                                         false,
                                         FmhaMasks::CausalMask,
                                         ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                         false,
                                         false,
                                         ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                         true,
                                         true,
                                         false,
                                         false,
                                         true,
                                         false>;
                    return fmha_fwd_<trait_, ck_tile::gfx950_t>(s, a);
                }
            }
        }
    }

    return r;
}
} // namespace ck_tile